name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
          submodules: true
      - run: | 
          echo ${{ github.event.client_payload.sha }}
          git config --global user.name "akss13"
          git config --global user.email "aakarsh.s.saini@gmail.com"
          git submodule sync --recursive
          git add -A
          git commit -a -m "updated submodules"
          git push
